### ISSUE TITLE
Fix the introduction in the site

### ISSUE THREAD

**Issue by suhothayan** [siddhi-io/siddhi-map-csv#9]
**Description:**
The introduction doesn't make sense 

The siddhi-map-csv extension is an extension to Siddhi that provides the functionality to convert canonical events of the server in the WSO2Event format to any csv message format and convert events of any csv format to the server's canonical event format (WSO2Event) for processing.

**Comment by Niveathika92** [comment]
This can be closed with changes done in https://github.com/wso2-extensions/siddhi-map-csv/commit/f30649d3ab4c5d20b6bf09dad3b4eda6485bd27d
